version: '2'

services:
  postgres:
    image: 'postgres:9.5'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  app:
    depends_on:
      - 'postgres'
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/usr/src/app'
    volumes_from:
      - bundle
    env_file:
      - '.env'

  bundle:
    image: noponto_app
    volumes:
      - /bundle

volumes:
  postgres:
