version: '2'

services:
  postgres:
    image: 'postgres:9.5'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  app:
    depends_on:
      - 'postgres'
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/usr/src/app'

  bundle:
    image: noponto_app
    #command: echo "I'm a little data container, short and stout..."
    volumes:
      - /bundle

volumes:
  postgres:
